---
name: CI

on:
  pull_request:
    branches:
    - main
    workflow_dispatch:

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Python 3.10 Setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Environment Setup
      run: |
        pip install pipenv
        pipenv install --dev

    - name: Run pre-commit Hooks
      run: pipenv run pre-commit run --show-diff-on-failure --color-always --all-files --hook-stage manual
